source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'sqlite3'

gem 'rspec-rails'
gem 'capybara'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

